import { ArrowRight, Activity, GitBranch, Gauge, Sparkles, ShieldCheck, Zap, Clock } from 'lucide-react';

export default function Hero() {
  return (
    <section className="relative pt-36 pb-28 overflow-hidden noise">
      {/* Background layers */}
      <div className="absolute inset-0 bg-grid [mask-image:radial-gradient(ellipse_70%_50%_at_50%_0%,black_40%,transparent_80%)]" />
      <div className="absolute -top-32 left-1/2 -translate-x-1/2 w-[800px] h-[600px] bg-atlas-500/12 rounded-full blur-[140px] pointer-events-none" />
      <div className="absolute top-32 right-0 w-[360px] h-[360px] bg-indigo-500/8 rounded-full blur-[120px] pointer-events-none" />
      <div className="absolute top-64 left-0 w-[300px] h-[300px] bg-sky-500/6 rounded-full blur-[100px] pointer-events-none" />

      <div className="relative max-w-7xl mx-auto px-5 sm:px-8">
        <div className="grid lg:grid-cols-12 gap-12 items-center">
          {/* Left: copy */}
          <div className="lg:col-span-6">
            <div className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/[0.03] px-3.5 py-1.5 text-[12px] text-slate-300 mb-7 animate-fade-up">
              <span className="relative flex h-2 w-2">
                <span className="absolute inline-flex h-full w-full rounded-full bg-atlas-400 opacity-60 animate-pulse-ring" />
                <span className="relative inline-flex rounded-full h-2 w-2 bg-atlas-400" />
              </span>
              AI-Powered Legacy Modernization Platform
            </div>

            <h1 className="text-[2.6rem] sm:text-5xl md:text-[3.7rem] font-extrabold tracking-[-0.02em] leading-[1.06] animate-fade-up">
              Modernize legacy
              <br />
              systems with{' '}
              <span className="text-gradient">confidence</span>.
            </h1>

            <p className="mt-6 text-[17px] text-slate-300/90 leading-[1.65] max-w-xl animate-fade-up" style={{ animationDelay: '0.1s' }}>
              ATLAS turns months of manual assessment into minutes. Upload your
              codebase and get a health score, architecture map, impact analysis, effort
              estimates, and a migration roadmap — generated by AI.
            </p>

            <div className="mt-9 flex flex-col sm:flex-row items-start sm:items-center gap-3.5 animate-fade-up" style={{ animationDelay: '0.2s' }}>
              <a
                href="/app"
                className="group relative inline-flex items-center gap-2 rounded-full bg-gradient-to-r from-atlas-400 to-indigo-500 text-white font-semibold px-7 py-3.5 text-[15px] glow-cyan hover:brightness-110 transition-all duration-300"
              >
                Try it now
                <ArrowRight className="w-[18px] h-[18px] group-hover:translate-x-0.5 transition-transform duration-300" />
              </a>
              <a
                href="#how"
                className="inline-flex items-center gap-2 rounded-full border border-white/12 text-slate-200 font-medium px-6 py-3.5 text-[15px] hover:bg-white/[0.04] hover:border-white/20 transition-all duration-300"
              >
                See how it works
              </a>
            </div>

            {/* Trust indicators */}
            <div className="mt-10 flex flex-wrap items-center gap-x-6 gap-y-3 animate-fade-up" style={{ animationDelay: '0.3s' }}>
              <Trust icon={<Clock className="w-4 h-4" />} text="Results in minutes" />
              <Trust icon={<ShieldCheck className="w-4 h-4" />} text="Private & secure" />
              <Trust icon={<Zap className="w-4 h-4" />} text="No setup required" />
            </div>
          </div>

          {/* Right: dashboard preview */}
          <div className="lg:col-span-6 animate-fade-up" style={{ animationDelay: '0.35s' }}>
            <HeroDashboard />
          </div>
        </div>
      </div>
    </section>
  );
}

function Trust({ icon, text }: { icon: React.ReactNode; text: string }) {
  return (
    <span className="inline-flex items-center gap-2 text-[12.5px] text-slate-400">
      <span className="text-atlas-400">{icon}</span>
      {text}
    </span>
  );
}

function HeroDashboard() {
  return (
    <div className="relative">
      {/* glow behind */}
      <div className="absolute -inset-4 bg-gradient-to-tr from-atlas-500/20 via-indigo-500/10 to-transparent blur-3xl rounded-[2rem] pointer-events-none" />

      <div className="relative rounded-2xl border border-white/10 glass p-5 sm:p-6 shadow-2xl shadow-ink-950/50">
        {/* window bar */}
        <div className="flex items-center justify-between mb-5">
          <div className="flex items-center gap-2">
            <span className="w-3 h-3 rounded-full bg-rose-400/60" />
            <span className="w-3 h-3 rounded-full bg-amber-400/60" />
            <span className="w-3 h-3 rounded-full bg-emerald-400/60" />
          </div>
          <span className="text-[10.5px] text-slate-500 font-mono tracking-tight">atlas — analysis dashboard</span>
          <span className="w-12" />
        </div>

        {/* metric cards */}
        <div className="grid grid-cols-3 gap-3">
          <MetricCard
            icon={<Activity className="w-[18px] h-[18px]" />}
            label="Health Score"
            value="72"
            suffix="/100"
            tone="cyan"
            sub="Moderate"
          />
          <MetricCard
            icon={<Gauge className="w-[18px] h-[18px]" />}
            label="Est. Effort"
            value="480"
            suffix="hrs"
            tone="indigo"
            sub="6 months"
          />
          <MetricCard
            icon={<GitBranch className="w-[18px] h-[18px]" />}
            label="Risk Level"
            value="Med"
            suffix=""
            tone="emerald"
            sub="5 hotspots"
          />
        </div>

        {/* health bar */}
        <div className="mt-5 rounded-xl border border-white/[0.06] bg-ink-900/50 p-4">
          <div className="flex items-center justify-between mb-2.5">
            <span className="text-[11px] text-slate-400 font-medium">Codebase Health Distribution</span>
            <span className="text-[10px] text-slate-500 font-mono">1,284 files</span>
          </div>
          <div className="grid grid-cols-12 gap-1 h-2.5 rounded-full overflow-hidden">
            <div className="col-span-3 bg-emerald-400/80" />
            <div className="col-span-4 bg-atlas-400/80" />
            <div className="col-span-3 bg-amber-400/70" />
            <div className="col-span-2 bg-rose-400/70" />
          </div>
          <div className="mt-2 flex justify-between text-[9.5px] text-slate-500">
            <span>Good · 30%</span>
            <span>Moderate · 40%</span>
            <span>At risk · 22%</span>
            <span>Critical · 8%</span>
          </div>
        </div>

        {/* mini insight rows */}
        <div className="mt-3 space-y-2">
          <InsightRow label="Business rules extracted" value="147" />
          <InsightRow label="Dependencies mapped" value="892" />
          <InsightRow label="Critical paths identified" value="12" />
        </div>
      </div>

      {/* floating badge */}
      <div className="absolute -bottom-5 -left-5 hidden sm:flex items-center gap-2.5 rounded-xl border border-white/10 glass px-4 py-3 shadow-xl animate-float">
        <span className="grid place-items-center w-8 h-8 rounded-lg bg-emerald-500/15 text-emerald-400">
          <Sparkles className="w-4 h-4" />
        </span>
        <div>
          <div className="text-[11px] text-slate-400">Analysis complete</div>
          <div className="text-[12.5px] font-semibold text-white">in 4.2 minutes</div>
        </div>
      </div>
    </div>
  );
}

function MetricCard({
  icon,
  label,
  value,
  suffix,
  tone,
  sub,
}: {
  icon: React.ReactNode;
  label: string;
  value: string;
  suffix: string;
  tone: 'cyan' | 'indigo' | 'emerald';
  sub: string;
}) {
  const tones = {
    cyan: 'text-atlas-300 bg-atlas-500/12',
    indigo: 'text-indigo-300 bg-indigo-500/12',
    emerald: 'text-emerald-300 bg-emerald-500/12',
  };
  return (
    <div className="rounded-xl border border-white/[0.07] bg-ink-900/40 p-3.5">
      <div className={`grid place-items-center w-8 h-8 rounded-lg ${tones[tone]} mb-2.5`}>
        {icon}
      </div>
      <div className="text-[10px] text-slate-400 mb-1">{label}</div>
      <div className="flex items-baseline gap-1">
        <span className="text-lg font-bold text-white tracking-tight">{value}</span>
        <span className="text-[10px] text-slate-500">{suffix}</span>
      </div>
      <div className="text-[10px] text-slate-500 mt-0.5">{sub}</div>
    </div>
  );
}

function InsightRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between rounded-lg border border-white/[0.05] bg-ink-900/40 px-3.5 py-2.5">
      <span className="text-[11.5px] text-slate-400">{label}</span>
      <span className="text-[12.5px] font-semibold text-white font-mono">{value}</span>
    </div>
  );
}
